[profile.default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
# debug revert strings looks experimental and fails the CI because of an unexpected error.
revert_strings = "default"
names = true
sizes = true

[profile.default.fuzz]
runs = 1024

[profile.compound]
src = "contracts/compound/"
test = "test-foundry/compound/"
fork_block_number = 15_581_371

[profile.aave-v2]
src = "contracts/aave-v2/"
test = "test-foundry/aave-v2/"
fork_block_number = 15_581_371 # Block number when the Aave's V2 IRM was updated for the stETH.

[profile.aave-v3]
src = "contracts/aave-v3/"
test = "test-foundry/aave-v3/"
eth_rpc_url = "https://api.avax.network/ext/bc/C/rpc"
fork_block_number = 15_675_271
