name: Storage layout checks
description: Checks the storage layout does not collide with previous versions of a given contract.

inputs:
  path:
    description: The path to the contract source file.
    required: true
  protocol:
    description: The protocol on which the contract is built.
    required: true
  contract:
    description: The name of the contract of which to check the storage layout.
    required: true

runs:
  using: composite
  steps:
    - name: Generate storage layout
      run: forge inspect ${{ inputs.path }}:${{ inputs.contract }} storage-layout | tee ${{ inputs.protocol }}.${{ inputs.contract }}.storage_layout.json
      shell: bash

    - name: Check storage layout
      uses: Rubilmax/foundry-storage-diff@v1.1
      with:
        report: ${{ inputs.protocol }}.${{ inputs.contract }}.storage_layout.json
